name: Website Acceptance Tests
on:
  workflow_dispatch: {}
  workflow_run:
      workflows:
      - Website QA Deploy
      types:
        - completed

jobs:
  websiteAcceptanceTests:
    name: Run acceptance tests on website
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm --prefix ./acceptance-tests install
      - run: npm --prefix ./acceptance-tests run test-stage
      - run: npm --prefix ./acceptance-tests run test-production
